spring.application.name=Springwebservicerestapicrud
spring.datasource.url = jdbc:mysql://localhost:3306/restful_api_db
spring.datasource.username=root
spring.datasource.password=Sagar@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
